#import = [
	#"~/.config/alacritty/themes/doom_one.toml"
#]

[window]
opacity = 0.8

[font]
size = 11

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

# https://raw.githubusercontent.com/alacritty/alacritty-theme/master/themes/doom_one.toml
# Colors (Doom One)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#bbc2cf'

# Normal colors
[colors.normal]
black   = '#282c34'
red     = '#ff6c6b'
green   = '#98be65'
yellow  = '#ecbe7b'
blue    = '#51afef'
magenta = '#c678dd'
cyan    = '#46d9ff'
white   = '#bbc2cf'
